name: Test

on:
  push: {}
  pull_request: {}

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - run: npm ci
      - run: npm audit --audit-level=moderate
      - run: npx lockfile-lint --path package-lock.json --validate-https
      - run: npx web-ext lint --source-dir .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - run: npm ci
      - run: npm test